Actual Bowtie 2.44 update

diff --git a/src/bowtie2/Makefile b/src/bowtie2/Makefile
--- a/src/bowtie2/Makefile
+++ b/src/bowtie2/Makefile
@@ -21,121 +21,449 @@
 # Makefile for bowtie, bowtie2-build, bowtie2-inspect
 #
 
+PREFIX := /usr/local
+bindir := $(PREFIX)/bin
 
-INC_EXT = -I third_party
-LIBS_BT2 = -pthread
-#LIBS_BT2 = -lz -lpthread
-#CXX_STD = CXX11
+LDLIBS := -lpthread -lz
 
-MM_DEF = -DBOWTIE_MM
+HEADERS := $(wildcard *.h)
+BOWTIE_MM := 1
+BOWTIE_SHARED_MEM :=
 
+CXXFLAGS += -std=c++11
 
-EXTRA_FLAGS = -DPOPCNT_CAPABILITY
+ARCH = $(shell uname -m)
+NGS_VER ?= 2.9.2
+VDB_VER ?= 2.9.2-1
 
-SHARED_CPPS = ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp \
-              edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp \
-              reference.cpp ds.cpp multikey_qsort.cpp limit.cpp \
-			  random_source.cpp tinythread.cpp
+# Detect Cygwin or MinGW
+WINDOWS :=
+MINGW :=
+ifneq (,$(findstring MINGW,$(shell uname)))
+  WINDOWS := 1
+  MINGW := 1
+  # POSIX memory-mapped files not currently supported on Windows
+  BOWTIE_MM :=
+  BOWTIE_SHARED_MEM :=
+endif
 
+MACOS :=
+ifneq (,$(findstring Darwin,$(shell uname)))
+  MACOS := 1
+  ifeq (1,$(shell uname -r | awk -F. '{ if ($$1 > 12 && $$1 < 16) print 1; }'))
+	CXXFLAGS += -stdlib=libstdc++
+  endif
+  ifdef STATIC_BUILD
+	CXXFLAGS += -mmacosx-version-min=10.9
+  endif
+endif
 
+BITS := 32
+ifneq (,$(findstring $(shell uname -m), x86_64 amd64))
+  BITS := 64
+  SSE_FLAG := -msse2
+  POPCNT_CAPABILITY ?= 1
+else ifneq (,$(findstring $(shell uname -m), aarch64 arm64 s390x ppc64 ppc64le))
+  BITS := 64
+  SSE_FLAG :=
+  CXXFLAGS += -fopenmp-simd
+  CPPFLAGS += -Ithird_party
+  POPCNT_CAPABILITY ?= 0
+endif
 
-SEARCH_CPPS = qual.cpp pat.cpp sam.cpp \
-              read_qseq.cpp aligner_seed_policy.cpp \
-              aligner_seed.cpp \
-			  aligner_seed2.cpp \
-			  aligner_sw.cpp \
-			  aligner_sw_driver.cpp aligner_cache.cpp \
-			  aligner_result.cpp ref_coord.cpp mask.cpp \
-			  pe.cpp aln_sink.cpp dp_framer.cpp \
-			  scoring.cpp presets.cpp unique.cpp \
-			  simple_func.cpp \
-			  random_util.cpp \
-			  aligner_bt.cpp sse_util.cpp \
-			  aligner_swsse.cpp outq.cpp \
-			  aligner_swsse_loc_i16.cpp \
-			  aligner_swsse_ee_i16.cpp \
-			  aligner_swsse_loc_u8.cpp \
-			  aligner_swsse_ee_u8.cpp \
-			  aligner_driver.cpp
+# msys will always be 32 bit so look at the cpu arch instead.
+ifneq (,$(findstring AMD64,$(PROCESSOR_ARCHITEW6432)))
+  ifeq (1,$(MINGW))
+    BITS := 64
+  endif
+endif
+ifeq (32,$(BITS))
+  $(error bowtie2 compilation requires a 64-bit platform )
+endif
 
-SEARCH_CPPS_MAIN = $(SEARCH_CPPS) bowtie_main.cpp
+ifdef STATIC_BUILD
+  LDFLAGS += -L$(CURDIR)/.tmp/lib
+  CPPFLAGS += -I$(CURDIR)/.tmp/include
+endif
 
-DP_CPPS = qual.cpp aligner_sw.cpp aligner_result.cpp ref_coord.cpp mask.cpp \
-          simple_func.cpp sse_util.cpp aligner_bt.cpp aligner_swsse.cpp \
-		  aligner_swsse_loc_i16.cpp aligner_swsse_ee_i16.cpp \
-		  aligner_swsse_loc_u8.cpp aligner_swsse_ee_u8.cpp scoring.cpp
+ifeq (1, $(POPCNT_CAPABILITY))
+  CXXFLAGS += -DPOPCNT_CAPABILITY
+  CPPFLAGS += -I third_party
+endif
 
-BUILD_CPPS = diff_sample.cpp
-BUILD_CPPS_MAIN = $(BUILD_CPPS) bowtie_build_main.cpp
+MM_DEF :=
 
+ifeq (1,$(BOWTIE_MM))
+  MM_DEF := -DBOWTIE_MM
+endif
 
-VERSION = 2.4.4
+SHMEM_DEF :=
 
+ifdef BOWTIE_SHARED_MEM
+  SHMEM_DEF := -DBOWTIE_SHARED_MEM
+endif
 
-SSE_FLAG=-msse2
+PTHREAD_PKG :=
+PTHREAD_LIB :=
 
+ifeq (1,$(MINGW))
+  PTHREAD_LIB :=
+else
+  PTHREAD_LIB := -lpthread
+endif
 
-RELEASE_FLAGS  = -O3 -m64 $(SSE_FLAG) -funroll-loops -g3
-RELEASE_DEFS   = -DCOMPILER_OPTIONS="\"$(RELEASE_FLAGS) $(EXTRA_FLAGS)\""
-NOASSERT_FLAGS = -DNDEBUG
-FILE_FLAGS     = -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
+ifeq (1,$(NO_SPINLOCK))
+  CXXFLAGS += -DNO_SPINLOCK
+endif
 
+USE_SRA ?=
+ifeq (1, $(USE_SRA))
+  ifdef MINGW
+    $(error "SRA binaries cannot be built on MINGW")
+  else
+    LDFLAGS += -L$(CURDIR)/.tmp/lib64
+    ifndef ($(STATIC_BUILD))
+      CPPFLAGS += -I$(CURDIR)/.tmp/include
+    endif
+    LDLIBS += -lncbi-ngs-c++-static
+    LDLIBS += -lngs-c++-static
+    LDLIBS += -lncbi-vdb-static
+    LDLIBS += -ldl
+    CXXFLAGS += -DUSE_SRA
+  endif
+endif
 
+ifeq (1,$(WITH_THREAD_PROFILING))
+  CXXFLAGS += -DPER_THREAD_TIMING=1
+endif
 
+ifeq (1,$(WITH_AFFINITY))
+  CXXFLAGS += -DWITH_AFFINITY=1
+endif
 
-DEFS=-fno-strict-aliasing \
-     -DBOWTIE2_VERSION="\"2.4.4\"" \
-     -DBUILD_HOST="\"Rbowtie2\"" \
-     -DBUILD_TIME="\"2017\"" \
-     -DCOMPILER_VERSION="\"C++11\"" \
-     $(FILE_FLAGS) \
-     $(MM_DEF) \
+#default is to use queue lock for better thread scaling performance
+ifneq (1,$(NO_QUEUELOCK))
+  CXXFLAGS += -DNO_SPINLOCK
+  CXXFLAGS += -DWITH_QUEUELOCK=1
+endif
 
+SHARED_CPPS :=  ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp \
+  edit.cpp bt2_locks.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp \
+  reference.cpp ds.cpp multikey_qsort.cpp limit.cpp \
+  random_source.cpp
 
-CPPFLAGS = $(RELEASE_DEFS) $(EXTRA_FLAGS) $(DEFS) -DBOWTIE2 \
-               $(NOASSERT_FLAGS) $(INC_EXT) $(LIBS_BT2)  
+SEARCH_CPPS :=  qual.cpp pat.cpp sam.cpp \
+  read_qseq.cpp aligner_seed_policy.cpp \
+  aligner_seed.cpp \
+  aligner_seed2.cpp \
+  aligner_sw.cpp \
+  aligner_sw_driver.cpp aligner_cache.cpp \
+  aligner_result.cpp ref_coord.cpp mask.cpp \
+  pe.cpp aln_sink.cpp dp_framer.cpp \
+  scoring.cpp presets.cpp unique.cpp \
+  simple_func.cpp \
+  random_util.cpp \
+  aligner_bt.cpp sse_util.cpp \
+  aligner_swsse.cpp outq.cpp \
+  aligner_swsse_loc_i16.cpp \
+  aligner_swsse_ee_i16.cpp \
+  aligner_swsse_loc_u8.cpp \
+  aligner_swsse_ee_u8.cpp \
+  aligner_driver.cpp
 
+ifeq (1, $(WITH_ZSTD))
+  LDLIBS += -lzstd
+  SHARED_CPPS += zstd_decompress.cpp
+endif
 
-CXXFLAGS = $(RELEASE_FLAGS) -Wall
+SEARCH_CPPS_MAIN := $(SEARCH_CPPS) bowtie_main.cpp
 
+DP_CPPS := qual.cpp aligner_sw.cpp aligner_result.cpp ref_coord.cpp mask.cpp \
+  simple_func.cpp sse_util.cpp aligner_bt.cpp aligner_swsse.cpp \
+  aligner_swsse_loc_i16.cpp aligner_swsse_ee_i16.cpp \
+  aligner_swsse_loc_u8.cpp aligner_swsse_ee_u8.cpp scoring.cpp
 
+BUILD_CPPS := diff_sample.cpp
+BUILD_CPPS_MAIN := $(BUILD_CPPS) bowtie_build_main.cpp
 
-SRCS_SEARCH = bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) bowtie_main.cpp
+SEARCH_FRAGMENTS := $(wildcard search_*_phase*.c)
+VERSION := $(shell cat BOWTIE2_VERSION)
 
-SRCS_BUILD = bt2_build.cpp $(SHARED_CPPS) $(HEADERS) bowtie_build_main.cpp diff_sample.cpp
+SANITIZER_FLAGS :=
+ifeq (0,$(shell $(CXX) -E -fsanitize=address,undefined btypes.h > /dev/null 2>&1; echo $$?))
+  SANITIZER_FLAGS := -fsanitize=address,undefined
+else ifeq (0,$(shell $(CXX) -E -fsanitize=address btypes.h > /dev/null 2>&1; echo $$?))
+  SANITIZER_FLAGS := -fsanitize=address
+else ifeq (0,$(shell $(CXX) -E -fsanitize=undefined btypes.h > /dev/null 2>&1; echo $$?))
+  SANITIZER_FLAGS := -fsanitize=undefined
+endif
 
-OBJS_SEARCH = $(SRCS_SEARCH:.cpp=.o)
+DEBUG_FLAGS    := -O0 -g3 $(SSE_FLAG)
+RELEASE_FLAGS  := -O3 $(SSE_FLAG) -funroll-loops -g3
+NOASSERT_FLAGS := -DNDEBUG
+FILE_FLAGS     := -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
+DEBUG_DEFS     = -DCOMPILER_OPTIONS="\"$(DEBUG_FLAGS) $(CXXFLAGS)\""
+RELEASE_DEFS   = -DCOMPILER_OPTIONS="\"$(RELEASE_FLAGS) $(CXXFLAGS)\""
 
-OBJS_BUILD = $(SRCS_BUILD:.cpp=.o)
+BOWTIE2_BIN_LIST := bowtie2-build-s \
+  bowtie2-build-l \
+  bowtie2-align-s \
+  bowtie2-align-l \
+  bowtie2-inspect-s \
+  bowtie2-inspect-l
+BOWTIE2_BIN_LIST_DBG := bowtie2-build-s-debug \
+  bowtie2-build-l-debug \
+  bowtie2-align-s-debug \
+  bowtie2-align-l-debug \
+  bowtie2-inspect-s-debug \
+  bowtie2-inspect-l-debug
+BOWTIE2_BIN_LIST_SAN := bowtie2-build-s-sanitized \
+  bowtie2-build-l-sanitized \
+  bowtie2-align-s-sanitized \
+  bowtie2-align-l-sanitized \
+  bowtie2-inspect-s-sanitized \
+  bowtie2-inspect-l-sanitized
+ifndef SANITIZER_FLAGS
+        BOWTIE2_BIN_LIST_SAN =
+endif
 
-.PHONY: all clean bowtie2-align-s bowtie2-build-s
+GENERAL_LIST := $(wildcard scripts/*.sh) \
+  $(wildcard scripts/*.pl) \
+  doc/manual.html \
+  doc/README \
+  doc/style.css \
+  $(wildcard example/index/*.bt2) \
+  $(wildcard example/reads/*.fq) \
+  $(wildcard example/reads/*.pl) \
+  example/reads/combined_reads.bam \
+  example/reference/lambda_virus.fa \
+  $(PTHREAD_PKG) \
+  bowtie2 \
+  bowtie2-build \
+  bowtie2-inspect \
+  AUTHORS \
+  LICENSE \
+  NEWS \
+  MANUAL \
+  MANUAL.markdown \
+  README.md \
+  TUTORIAL \
+  BOWTIE2_VERSION
 
-all: bowtie2-build-s bowtie2-align-s bowtie2-build-l bowtie2-align-l
+ifeq (1,$(WINDOWS))
+  BOWTIE2_BIN_LIST := $(BOWTIE2_BIN_LIST) bowtie2.bat bowtie2-build.bat bowtie2-inspect.bat
+  CXXFLAGS += -static-libgcc -static-libstdc++
+endif
+
+# This is helpful on Windows under MinGW/MSYS, where Make might go for
+# the Windows FIND tool instead.
+FIND := $(shell which find)
+
+SRC_PKG_LIST = $(wildcard *.h) \
+  $(wildcard *.hh) \
+  $(wildcard *.c) \
+  $(wildcard *.cpp) \
+  $(wildcard third_party/*) \
+  Makefile \
+  CMakeLists.txt \
+  $(GENERAL_LIST)
+
+ifeq (1,$(WINDOWS))
+  BIN_PKG_LIST := $(GENERAL_LIST) bowtie2.bat bowtie2-build.bat bowtie2-inspect.bat
+else
+  BIN_PKG_LIST := $(GENERAL_LIST)
+endif
+
+.PHONY: all allall both both-debug
+
+all: $(BOWTIE2_BIN_LIST) ;
+allall: $(BOWTIE2_BIN_LIST) $(BOWTIE2_BIN_LIST_DBG) $(BOWTIE2_BIN_LIST_SAN) ;
+both: bowtie2-align-s bowtie2-build-s bowtie2-align-l bowtie2-build-l ;
+both-debug: bowtie2-align-s-debug bowtie2-build-s-debug bowtie2-align-l-debug bowtie2-build-l-debug ;
+both-sanitized: bowtie2-align-s-sanitized bowtie2-build-s-sanitized bowtie2-align-l-sanitized bowtie2-build-l-sanitized ;
+
+DEFS := -fno-strict-aliasing \
+  -DBOWTIE2_VERSION="\"`cat BOWTIE2_VERSION`\"" \
+  -DBUILD_HOST="\"$${HOSTNAME:-`hostname`}\"" \
+  -DBUILD_TIME="\"`date -u`\"" \
+  -DCOMPILER_VERSION="\"`$(CXX) -v 2>&1 | tail -1`\"" \
+  $(FILE_FLAGS) \
+  $(PREF_DEF) \
+  $(MM_DEF) \
+  $(SHMEM_DEF)
+
+# set compiler flags for all sanitized builds
+ifdef BOWTIE2_BIN_LIST_SAN
+$(BOWTIE2_BIN_LIST_SAN): CXXFLAGS+=$(SANITIZER_FLAGS)
+else
+$(BOWTIE2_BIN_LIST_SAN): $(error "Compiler does not support...")
+endif
+
+#
+# bowtie2-build targets
+#
+
+bowtie2-build-s-sanitized bowtie2-build-s: bt2_build.cpp $(SHARED_CPPS) $(HEADERS)
+	$(CXX) $(RELEASE_FLAGS) $(RELEASE_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 $(NOASSERT_FLAGS) -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(BUILD_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-build-l-sanitized bowtie2-build-l: bt2_build.cpp $(SHARED_CPPS) $(HEADERS)
+	$(CXX) $(RELEASE_FLAGS) $(RELEASE_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_64BIT_INDEX $(NOASSERT_FLAGS) -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(BUILD_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-build-s-debug: bt2_build.cpp $(SHARED_CPPS) $(HEADERS)
+	$(CXX) $(DEBUG_FLAGS) $(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(BUILD_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-build-l-debug: bt2_build.cpp $(SHARED_CPPS) $(HEADERS)
+	$(CXX) $(DEBUG_FLAGS) $(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_64BIT_INDEX -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(BUILD_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+#
+# bowtie2-align targets
+#
+
+bowtie2-align-s-sanitized bowtie2-align-s: bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) $(HEADERS) $(SEARCH_FRAGMENTS)
+	$(CXX) $(RELEASE_FLAGS) $(RELEASE_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 $(NOASSERT_FLAGS) -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(SEARCH_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-align-l-sanitized bowtie2-align-l: bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) $(HEADERS) $(SEARCH_FRAGMENTS)
+	$(CXX) $(RELEASE_FLAGS) $(RELEASE_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_64BIT_INDEX $(NOASSERT_FLAGS) -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(SEARCH_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-align-s-debug: bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) $(HEADERS) $(SEARCH_FRAGMENTS)
+	$(CXX) $(DEBUG_FLAGS) \
+		$(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(SEARCH_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-align-l-debug: bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) $(HEADERS) $(SEARCH_FRAGMENTS)
+	$(CXX) $(DEBUG_FLAGS) \
+		$(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_64BIT_INDEX -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) $(SEARCH_CPPS_MAIN) \
+		$(LDFLAGS) $(LDLIBS)
+
+#
+# bowtie2-inspect targets
+#
+
+bowtie2-inspect-s-sanitized bowtie2-inspect-s: bt2_inspect.cpp $(HEADERS) $(SHARED_CPPS)
+	$(CXX) $(RELEASE_FLAGS) \
+		$(RELEASE_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_INSPECT_MAIN -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-inspect-l-sanitized bowtie2-inspect-l: bt2_inspect.cpp $(HEADERS) $(SHARED_CPPS)
+	$(CXX) $(RELEASE_FLAGS) \
+		$(RELEASE_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_INSPECT_MAIN  -DBOWTIE_64BIT_INDEX -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-inspect-s-debug: bt2_inspect.cpp $(HEADERS) $(SHARED_CPPS)
+	$(CXX) $(DEBUG_FLAGS) \
+		$(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_INSPECT_MAIN -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-inspect-l-debug: bt2_inspect.cpp $(HEADERS) $(SHARED_CPPS)
+	$(CXX) $(DEBUG_FLAGS) \
+		$(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_64BIT_INDEX -DBOWTIE_INSPECT_MAIN -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(SHARED_CPPS) \
+		$(LDFLAGS) $(LDLIBS)
+
+#
+# bowtie2-dp targets
+#
+
+bowtie2-dp: bt2_dp.cpp $(HEADERS) $(SHARED_CPPS) $(DP_CPPS)
+	$(CXX) $(RELEASE_FLAGS) \
+		$(RELEASE_DEFS) $(CXXFLAGS) $(NOASSERT_FLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_DP_MAIN -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(DP_CPPS) $(SHARED_CPPS) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2-dp-debug: bt2_dp.cpp $(HEADERS) $(SHARED_CPPS) $(DP_CPPS)
+	$(CXX) $(DEBUG_FLAGS) \
+		$(DEBUG_DEFS) $(CXXFLAGS) \
+		$(DEFS) -DBOWTIE2 -DBOWTIE_DP_MAIN -Wall \
+		$(CPPFLAGS) \
+		-o $@ $< \
+		$(DP_CPPS) $(SHARED_CPPS) \
+		$(LDFLAGS) $(LDLIBS)
+
+bowtie2.bat:
+	echo "@echo off" > bowtie2.bat
+	echo "perl %~dp0/bowtie2 %*" >> bowtie2.bat
+
+bowtie2-build.bat:
+	echo "@echo off" > bowtie2-build.bat
+	echo "python3 %~dp0/bowtie2-build %*" >> bowtie2-build.bat
+
+bowtie2-inspect.bat:
+	echo "@echo off" > bowtie2-inspect.bat
+	echo "python3 %~dp0/bowtie2-inspect %*" >> bowtie2-inspect.bat
+
+.PHONY: move
+move: bowtie2-build-s bowtie2-align-s bowtie2-build-l bowtie2-align-l
 	cp bowtie2-align-s ../../inst
 	cp bowtie2-build-s ../../inst
 	cp bowtie2-align-l ../../inst
 	cp bowtie2-build-l ../../inst
 
 
-.cc.o:
-	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< 
-
- 
-
-bowtie2-build-s: $(OBJS_BUILD)
-	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $^
-	
-bowtie2-build-l: $(OBJS_BUILD)
-	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $^
-	
-bowtie2-align-s: $(OBJS_SEARCH)
-	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $^ 
-	
-bowtie2-align-l: $(OBJS_SEARCH)
-	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $^ 
-
-
+.PHONY: clean
 clean:
+	rm -f $(BOWTIE2_BIN_LIST) $(BOWTIE2_BIN_LIST_DBG) $(BOWTIE2_BIN_LIST_SAN) \
+	$(addsuffix .exe,$(BOWTIE2_BIN_LIST) $(BOWTIE2_BIN_LIST_DBG)) \
+	bowtie2-*.zip
+	rm -f core.* .tmp.head
+	rm -rf *.dSYM
+	rm -rf .tmp
+	
 	rm -f ../../inst/bowtie2-align-s
 	rm -f ../../inst/bowtie2-build-s
 	rm -f ../../inst/bowtie2-align-l
@@ -145,3 +473,11 @@ clean:
 	rm -f bowtie2-align-l
 	rm -f bowtie2-build-l
 	rm -f *.o
+	
+	
+
+	
+	
+
+	
+
